"""Initial migration

Revision ID: e1958abb9257
Revises:
Create Date: 2026-01-09 19:01:59.152431

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1958abb9257"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("includes_vat", sa.Boolean(), nullable=True),
        sa.Column("min_order_amount", sa.Float(), nullable=True),
        sa.Column("last_catalog_update", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=True)
    op.create_table(
        "alias_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("raw_name_from_distributor", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alias_map_raw_name_from_distributor"),
        "alias_map",
        ["raw_name_from_distributor"],
        unique=True,
    )
    op.create_table(
        "catalogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distributor_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["distributor_id"],
            ["distributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_id", sa.Integer(), nullable=True),
        sa.Column("raw_name", sa.String(), nullable=False),
        sa.Column("base_price", sa.Float(), nullable=False),
        sa.Column("discount", sa.Float(), nullable=True),
        sa.Column("effective_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["catalogs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_price",
        "product_catalog",
        ["raw_name", "effective_price"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_catalog_effective_price"),
        "product_catalog",
        ["effective_price"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_product_catalog_effective_price"), table_name="product_catalog"
    )
    op.drop_index("idx_product_price", table_name="product_catalog")
    op.drop_table("product_catalog")
    op.drop_table("catalogs")
    op.drop_index(
        op.f("ix_alias_map_raw_name_from_distributor"), table_name="alias_map"
    )
    op.drop_table("alias_map")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_table("products")
    op.drop_table("distributors")
    # ### end Alembic commands ###
